"""
Knowledge base for the FAQ Chatbot capstone project.
Expanded from 15 -> 27 Q&A pairs (12 new questions added for the capstone),
covering the same scope: beginner CS/programming fundamentals.
"""

KNOWLEDGE_BASE = [
    {"id": 1, "question": "Compiler vs. interpreter?",
     "answer": "A compiler translates the whole source code into machine code before execution, producing a standalone executable. An interpreter translates and executes code line by line at runtime."},
    {"id": 2, "question": "What is Git and why use it?",
     "answer": "Git is a distributed version control system that tracks code changes over time, enabling collaboration and rollback to earlier versions."},
    {"id": 3, "question": "Frontend vs. backend?",
     "answer": "Frontend builds what users interact with directly (UI, layout). Backend handles server-side logic, databases, and APIs."},
    {"id": 4, "question": "What is an API?",
     "answer": "An API is a set of rules letting software systems communicate, typically via requests and responses."},
    {"id": 5, "question": "Array vs. linked list?",
     "answer": "Arrays store elements in contiguous memory for fast index access. Linked lists store elements as pointer-connected nodes, faster to insert/remove but slower to access by index."},
    {"id": 6, "question": "What is Big O notation?",
     "answer": "It describes how an algorithm's runtime or memory use grows as input size increases, used to compare efficiency."},
    {"id": 7, "question": "SQL vs. NoSQL?",
     "answer": "SQL databases use structured tables with fixed schemas. NoSQL databases store flexible formats (documents, key-value, graphs), suited to unstructured data."},
    {"id": 8, "question": "What is OOP (object-oriented programming)?",
     "answer": "A paradigm organizing code into objects combining data and behavior, built on encapsulation, inheritance, and polymorphism."},
    {"id": 9, "question": "Best first language for beginners?",
     "answer": "Python is commonly recommended for its readable syntax and wide use in web dev, data science, and automation."},
    {"id": 10, "question": "HTTP vs. HTTPS?",
     "answer": "HTTPS is HTTP encrypted with TLS/SSL, protecting data in transit from interception."},
    {"id": 11, "question": "What is a database index?",
     "answer": "A structure that speeds up data retrieval on a table, at the cost of extra storage and slower writes."},
    {"id": 12, "question": "What is branching in version control?",
     "answer": "A separate line of development from the main codebase, used for features/fixes without affecting main until merged."},
    {"id": 13, "question": "Synchronous vs. asynchronous code?",
     "answer": "Synchronous code blocks until each operation finishes; asynchronous code lets other work run while waiting on a task."},
    {"id": 14, "question": "What is a REST API?",
     "answer": "An API following REST principles, using HTTP methods (GET, POST, PUT, DELETE) on URL-identified resources."},
    {"id": 15, "question": "Bug vs. feature request?",
     "answer": "A bug is unintended behavior where software doesn't work as designed; a feature request asks for new functionality."},
    # --- 12 new questions added for the Week 8 capstone ---
    {"id": 16, "question": "What is recursion?",
     "answer": "Recursion is when a function calls itself to solve a smaller version of the same problem, until it reaches a base case that stops it."},
    {"id": 17, "question": "Stack vs. queue?",
     "answer": "A stack is Last-In-First-Out (LIFO): the last item added is the first removed. A queue is First-In-First-Out (FIFO): the first item added is the first removed."},
    {"id": 18, "question": "TCP vs. UDP?",
     "answer": "TCP is connection-based and guarantees ordered, reliable delivery. UDP is connectionless and faster, but does not guarantee delivery or order."},
    {"id": 19, "question": "What is caching?",
     "answer": "Caching stores frequently used data in fast, temporary storage so future requests for it are served faster instead of recomputing or refetching it."},
    {"id": 20, "question": "What is encryption?",
     "answer": "Encryption converts readable data into an unreadable format using a key, so only someone with the correct key can decrypt and read it again."},
    {"id": 21, "question": "What is unit testing?",
     "answer": "Unit testing means testing small, individual pieces of code (like a single function) in isolation to confirm each one works as expected."},
    {"id": 22, "question": "What is JSON?",
     "answer": "JSON (JavaScript Object Notation) is a lightweight, text-based format for storing and exchanging data using key-value pairs, widely used by APIs."},
    {"id": 23, "question": "What is cloud computing?",
     "answer": "Cloud computing means renting computing resources (servers, storage, databases) over the internet instead of owning physical hardware."},
    {"id": 24, "question": "What is Agile/Scrum?",
     "answer": "Agile is a software development approach based on short, iterative cycles. Scrum is a specific Agile framework using fixed-length sprints, daily stand-ups, and a backlog."},
    {"id": 25, "question": "What is exception handling?",
     "answer": "Exception handling is code that catches and responds to runtime errors (using try/except or try/catch) so the program can fail gracefully instead of crashing."},
    {"id": 26, "question": "Primary key vs. foreign key?",
     "answer": "A primary key uniquely identifies each row in a table. A foreign key is a column in one table that references a primary key in another table, linking the two."},
    {"id": 27, "question": "What is version control merging?",
     "answer": "Merging combines changes from one branch into another, integrating the work of separate branches back into a single line of code."},
]
